/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/casa.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone.geometry}
        material={materials["Twisted Raffia"]}
        position={[0.01, 7.3, -0.02]}
        scale={[5.5, 5.53, 5.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Clay raw"]}
        position={[0.05, -8.33, 0.07]}
        scale={4.95}
      />
    </group>
  );
}

useGLTF.preload("/casa.glb");